In [1]:
import pandas as pd
import numpy as np
import networkx as nx

In [2]:
df = pd.read_csv("/Users/jennie/Desktop/INFO6850/networks-paper-1/scratch/opp_migration_with_features.csv")
od_pooled = pd.read_csv("/Users/jennie/Desktop/INFO6850/networks-paper-1/scratch/od_pooled.csv")

In [3]:
df['o_cz'] = df['o_cz'].astype(str)
df['d_cz'] = df['d_cz'].astype(str)

df['o_cz_name'] = od_pooled['o_cz_name']
df['d_cz_name'] = od_pooled['d_cz_name']
df['o_state_name'] = od_pooled['o_state_name']
df['d_state_name'] = od_pooled['d_state_name']

In [4]:
p = []
p_ = []
for i in df.columns:
    if "o_" in i:
        p.append(i)
    elif "d_" in i:
        p_.append(i)

In [5]:
o = df[p].drop_duplicates()
o.columns = o.columns.str.replace("o_",'')
d = df[p_].drop_duplicates()
d.columns = d.columns.str.replace("d_","")
o = o.drop(['d_distance'], axis=1)

o = o.drop_duplicates()
d = d.rename(columns={'frac_between_p25_anp75':'frac_between_p25_and_p75', 'householincome_per_capita':'household_income_per_capita'})

In [6]:
node_list = pd.concat([o,d],axis=0).drop_duplicates().set_index('cz')
node_list

,census_2000_population,urban_areas,frac_black,racial_segregation,income_segregation,segregation_of_poverty_p25,segregation_of_affluence_p75,frac_with_commute_15_mins,household_income_per_capita,gini,...,frac_foreign_born,social_capital_index,fraction_religious,violent_crime_rate,fraction_of_children_with_single_mothers,fraction_of_adults_divorced,fraction_of_adults_married,income_growth_2000_2006_10,cz_name,state_name
cz,,,,,,,,,,,,,,,,,,,,,
6502,203077,1,0.032919,0.074607,0.035663,0.034944,0.036015,0.342682,30498.56,0.41775,...,0.015894,-0.643165,0.627210,0.002078,0.183695,0.114534,0.620598,-0.007689,Cleveland,Tennessee
34108,13913,0,0.009272,0.075959,0.028469,0.013208,0.030552,0.752053,38933.16,0.37145,...,0.166894,0.063928,0.256091,0.004263,0.137303,0.102063,0.603708,-0.017960,Kodiak,Alaska
10302,223605,1,0.212549,0.142392,0.049965,0.046493,0.055159,0.360896,32267.80,0.49754,...,0.019941,-1.400222,0.631837,0.001767,0.247671,0.107316,0.588684,-0.006666,Dothan,Alabama
5201,54214,1,0.184620,0.087787,0.010840,0.012030,0.010159,0.298675,27596.21,0.38927,...,0.017081,0.047149,0.734091,0.001881,0.195818,0.092145,0.599533,-0.012768,New Albany,Mississippi
29201,21441,0,0.009888,0.114814,0.007860,0.005462,0.005215,0.577805,34022.27,0.31682,...,0.008775,2.298457,0.744322,0.000420,0.149265,0.079023,0.609058,-0.001545,Hiawatha,Kansas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27302,49010,0,0.002408,0.052251,0.016920,0.021115,0.012920,0.575637,35647.91,0.29377,...,0.016343,2.860045,0.877800,0.000959,0.156558,0.072769,0.608053,0.007454,Fairmont,Minnesota
31101,165277,1,0.063536,0.119596,0.046627,0.033655,0.060355,0.424640,33598.83,0.47231,...,0.043681,-0.448870,0.702542,0.001446,0.201264,0.091609,0.592017,0.004485,Victoria,Texas
26604,7756,0,0.000258,0.140697,0.002856,0.004302,0.002541,0.708020,31321.75,0.27150,...,0.004920,2.378510,0.834193,0.000645,0.188876,0.082657,0.579427,0.027007,Mobridge,South Dakota
37400,2570609,1,0.063019,0.161150,0.093399,0.086383,0.099266,0.284846,39560.49,0.45135,...,0.147453,-0.596082,0.354011,0.004326,0.224732,0.111112,0.540825,-0.002059,Sacramento,California
37901,1568418,1,0.078189,0.137608,0.101955,0.092796,0.106357,0.245483,38428.77,0.51797,...,0.164997,-2.316924,0.352029,0.001649,0.220870,0.136466,0.532900,-0.005507,Las Vegas,Nevada

In [7]:
node_list = node_list.to_dict('index')

In [13]:
print("Importing migration data ...")
migration_net = nx.from_pandas_edgelist(
    df=df,
    source="o_cz",
    target="d_cz",
    edge_attr=True,
    create_using=nx.DiGraph
)

# print("Generating quick viz ...")
# pos = nx.spring_layout(G=migration_net, weight='n')
# nx.draw_networkx_nodes(migration_net, pos=pos)

print("Outputting network data ...")
nx.write_graphml(migration_net, "/Users/jennie/Desktop/INFO6850/networks-paper-1/scratch/migration_network.graphml")

Importing migration data ...
Outputting network data ...

In [ ]:
nx.set_node_attributes(migration_net, )